// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `yarn gen:registry` to regenerate.
/* eslint-disable */
import type { RegistryEntry, RevizComponent } from "./types";

import { meta as meta_0, default as Comp_0 } from "./components/charts/BarChart";

export const REGISTRY: RegistryEntry[] = [
  { meta: meta_0, Component: Comp_0 as unknown as RevizComponent },
];
