// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `yarn gen:registry` to regenerate.
/* eslint-disable */
import type { RegistryEntry, RevizComponent } from "./types";

import { meta as meta_0, default as Comp_0 } from "./components/charts/AreaChart";
import { meta as meta_1, default as Comp_1 } from "./components/charts/BarChart";
import { meta as meta_2, default as Comp_2 } from "./components/charts/BubbleChart";
import { meta as meta_3, default as Comp_3 } from "./components/charts/BumpChart";
import { meta as meta_4, default as Comp_4 } from "./components/charts/DonutChart";
import { meta as meta_5, default as Comp_5 } from "./components/charts/FunnelChart";
import { meta as meta_6, default as Comp_6 } from "./components/charts/GaugeChart";
import { meta as meta_7, default as Comp_7 } from "./components/charts/GroupedBarChart";
import { meta as meta_8, default as Comp_8 } from "./components/charts/Histogram";
import { meta as meta_9, default as Comp_9 } from "./components/charts/LineChart";
import { meta as meta_10, default as Comp_10 } from "./components/charts/RadarChart";
import { meta as meta_11, default as Comp_11 } from "./components/charts/ScatterPlot";
import { meta as meta_12, default as Comp_12 } from "./components/charts/SlopeChart";
import { meta as meta_13, default as Comp_13 } from "./components/charts/StackedBarChart";
import { meta as meta_14, default as Comp_14 } from "./components/charts/StepChart";
import { meta as meta_15, default as Comp_15 } from "./components/charts/Streamgraph";
import { meta as meta_16, default as Comp_16 } from "./components/charts/WaterfallChart";
import { meta as meta_17, default as Comp_17 } from "./components/data-display/CalendarHeatmap";
import { meta as meta_18, default as Comp_18 } from "./components/data-display/ComparisonTable";
import { meta as meta_19, default as Comp_19 } from "./components/data-display/DataTable";
import { meta as meta_20, default as Comp_20 } from "./components/data-display/GanttChart";
import { meta as meta_21, default as Comp_21 } from "./components/data-display/KPIGrid";
import { meta as meta_22, default as Comp_22 } from "./components/data-display/ProgressBarSet";
import { meta as meta_23, default as Comp_23 } from "./components/data-display/ProgressRing";
import { meta as meta_24, default as Comp_24 } from "./components/data-display/Sparkline";
import { meta as meta_25, default as Comp_25 } from "./components/data-display/StatCard";
import { meta as meta_26, default as Comp_26 } from "./components/data-display/Timeline";
import { meta as meta_27, default as Comp_27 } from "./components/diagrams/ArchitectureDiagram";
import { meta as meta_28, default as Comp_28 } from "./components/diagrams/ComparisonDiagram";
import { meta as meta_29, default as Comp_29 } from "./components/diagrams/ConceptMap";
import { meta as meta_30, default as Comp_30 } from "./components/diagrams/CycleDiagram";
import { meta as meta_31, default as Comp_31 } from "./components/diagrams/FlowDiagram";
import { meta as meta_32, default as Comp_32 } from "./components/diagrams/IsometricStack";
import { meta as meta_33, default as Comp_33 } from "./components/diagrams/NumberedSteps";
import { meta as meta_34, default as Comp_34 } from "./components/diagrams/PipelineDiagram";
import { meta as meta_35, default as Comp_35 } from "./components/diagrams/RadialConcept";
import { meta as meta_36, default as Comp_36 } from "./components/diagrams/SwimlaneDiagram";
import { meta as meta_37, default as Comp_37 } from "./components/diagrams/SystemTopology";
import { meta as meta_38, default as Comp_38 } from "./components/diagrams/VennDiagram";
import { meta as meta_39, default as Comp_39 } from "./components/interpretability/ActivationStrip";
import { meta as meta_40, default as Comp_40 } from "./components/interpretability/AnnotatedTranscript";
import { meta as meta_41, default as Comp_41 } from "./components/interpretability/AttentionHeadsGrid";
import { meta as meta_42, default as Comp_42 } from "./components/interpretability/AttentionMatrix";
import { meta as meta_43, default as Comp_43 } from "./components/interpretability/EmbeddingProjector";
import { meta as meta_44, default as Comp_44 } from "./components/interpretability/FeatureDashboard";
import { meta as meta_45, default as Comp_45 } from "./components/interpretability/LogitLens";
import { meta as meta_46, default as Comp_46 } from "./components/interpretability/NLAAutoencoder";
import { meta as meta_47, default as Comp_47 } from "./components/interpretability/ProbeResults";
import { meta as meta_48, default as Comp_48 } from "./components/interpretability/SaliencyText";
import { meta as meta_49, default as Comp_49 } from "./components/interpretability/TokenProbabilities";
import { meta as meta_50, default as Comp_50 } from "./components/layout-annotation/AnnotationBracket";
import { meta as meta_51, default as Comp_51 } from "./components/layout-annotation/AnnotationCallout";
import { meta as meta_52, default as Comp_52 } from "./components/layout-annotation/CitationBlock";
import { meta as meta_53, default as Comp_53 } from "./components/layout-annotation/ColorScaleLegend";
import { meta as meta_54, default as Comp_54 } from "./components/layout-annotation/HighlightBox";
import { meta as meta_55, default as Comp_55 } from "./components/layout-annotation/StepIndicator";
import { meta as meta_56, default as Comp_56 } from "./components/layout-annotation/TabGroup";
import { meta as meta_57, default as Comp_57 } from "./components/math/AlignedEquations";
import { meta as meta_58, default as Comp_58 } from "./components/math/DistributionPDF";
import { meta as meta_59, default as Comp_59 } from "./components/math/EquationBlock";
import { meta as meta_60, default as Comp_60 } from "./components/math/FunctionPlot";
import { meta as meta_61, default as Comp_61 } from "./components/math/IntegralArea";
import { meta as meta_62, default as Comp_62 } from "./components/math/MatrixDisplay";
import { meta as meta_63, default as Comp_63 } from "./components/math/NumberLine";
import { meta as meta_64, default as Comp_64 } from "./components/math/ParametricCurve";
import { meta as meta_65, default as Comp_65 } from "./components/math/UnitCircle";
import { meta as meta_66, default as Comp_66 } from "./components/math/VectorField";
import { meta as meta_67, default as Comp_67 } from "./components/ml-eval/AblationTable";
import { meta as meta_68, default as Comp_68 } from "./components/ml-eval/BenchmarkBars";
import { meta as meta_69, default as Comp_69 } from "./components/ml-eval/EvalGrid";
import { meta as meta_70, default as Comp_70 } from "./components/ml-eval/HyperparamSweep";
import { meta as meta_71, default as Comp_71 } from "./components/ml-eval/LatencyPercentiles";
import { meta as meta_72, default as Comp_72 } from "./components/ml-eval/Leaderboard";
import { meta as meta_73, default as Comp_73 } from "./components/ml-eval/LogScaleBars";
import { meta as meta_74, default as Comp_74 } from "./components/ml-eval/MetricScorecard";
import { meta as meta_75, default as Comp_75 } from "./components/ml-eval/ParetoFrontier";
import { meta as meta_76, default as Comp_76 } from "./components/ml-eval/RewardCurve";
import { meta as meta_77, default as Comp_77 } from "./components/ml-eval/ScalingLaw";
import { meta as meta_78, default as Comp_78 } from "./components/ml-eval/TrainingCurve";
import { meta as meta_79, default as Comp_79 } from "./components/ml-eval/WinRateMatrix";
import { meta as meta_80, default as Comp_80 } from "./components/robotics-media/CompareSlider";
import { meta as meta_81, default as Comp_81 } from "./components/robotics-media/EpisodeRollout";
import { meta as meta_82, default as Comp_82 } from "./components/robotics-media/FrameStrip";
import { meta as meta_83, default as Comp_83 } from "./components/robotics-media/HeatmapOverlay";
import { meta as meta_84, default as Comp_84 } from "./components/robotics-media/MediaCarousel";
import { meta as meta_85, default as Comp_85 } from "./components/robotics-media/ParticleField";
import { meta as meta_86, default as Comp_86 } from "./components/robotics-media/SyntheticDataTimeline";
import { meta as meta_87, default as Comp_87 } from "./components/robotics-media/TabbedCompare";
import { meta as meta_88, default as Comp_88 } from "./components/robotics-media/TrajectoryPlot";
import { meta as meta_89, default as Comp_89 } from "./components/statistical/BoxPlot";
import { meta as meta_90, default as Comp_90 } from "./components/statistical/CalibrationPlot";
import { meta as meta_91, default as Comp_91 } from "./components/statistical/ConfidenceBand";
import { meta as meta_92, default as Comp_92 } from "./components/statistical/ConfusionMatrix";
import { meta as meta_93, default as Comp_93 } from "./components/statistical/CorrelationMatrix";
import { meta as meta_94, default as Comp_94 } from "./components/statistical/ECDFPlot";
import { meta as meta_95, default as Comp_95 } from "./components/statistical/ForestPlot";
import { meta as meta_96, default as Comp_96 } from "./components/statistical/PRCurve";
import { meta as meta_97, default as Comp_97 } from "./components/statistical/QQPlot";
import { meta as meta_98, default as Comp_98 } from "./components/statistical/ROCCurve";
import { meta as meta_99, default as Comp_99 } from "./components/statistical/RegressionScatter";
import { meta as meta_100, default as Comp_100 } from "./components/statistical/ViolinPlot";
import { meta as meta_101, default as Comp_101 } from "./components/text-narrative/CalloutNote";
import { meta as meta_102, default as Comp_102 } from "./components/text-narrative/DefinitionBlock";
import { meta as meta_103, default as Comp_103 } from "./components/text-narrative/HighlightText";
import { meta as meta_104, default as Comp_104 } from "./components/text-narrative/KeyInsight";
import { meta as meta_105, default as Comp_105 } from "./components/text-narrative/PullQuote";
import { meta as meta_106, default as Comp_106 } from "./components/text-narrative/StatSentence";
import { meta as meta_107, default as Comp_107 } from "./components/text-narrative/TakeawaysList";
import { meta as meta_108, default as Comp_108 } from "./components/trees-graphs/AdjacencyMatrix";
import { meta as meta_109, default as Comp_109 } from "./components/trees-graphs/ChordDiagram";
import { meta as meta_110, default as Comp_110 } from "./components/trees-graphs/DAGFlow";
import { meta as meta_111, default as Comp_111 } from "./components/trees-graphs/DecisionTree";
import { meta as meta_112, default as Comp_112 } from "./components/trees-graphs/Dendrogram";
import { meta as meta_113, default as Comp_113 } from "./components/trees-graphs/ForceGraph";
import { meta as meta_114, default as Comp_114 } from "./components/trees-graphs/RadialTree";
import { meta as meta_115, default as Comp_115 } from "./components/trees-graphs/SankeyDiagram";
import { meta as meta_116, default as Comp_116 } from "./components/trees-graphs/SearchTree";
import { meta as meta_117, default as Comp_117 } from "./components/trees-graphs/Sunburst";
import { meta as meta_118, default as Comp_118 } from "./components/trees-graphs/Treemap";

export const REGISTRY: RegistryEntry[] = [
  { meta: meta_0, Component: Comp_0 as unknown as RevizComponent },
  { meta: meta_1, Component: Comp_1 as unknown as RevizComponent },
  { meta: meta_2, Component: Comp_2 as unknown as RevizComponent },
  { meta: meta_3, Component: Comp_3 as unknown as RevizComponent },
  { meta: meta_4, Component: Comp_4 as unknown as RevizComponent },
  { meta: meta_5, Component: Comp_5 as unknown as RevizComponent },
  { meta: meta_6, Component: Comp_6 as unknown as RevizComponent },
  { meta: meta_7, Component: Comp_7 as unknown as RevizComponent },
  { meta: meta_8, Component: Comp_8 as unknown as RevizComponent },
  { meta: meta_9, Component: Comp_9 as unknown as RevizComponent },
  { meta: meta_10, Component: Comp_10 as unknown as RevizComponent },
  { meta: meta_11, Component: Comp_11 as unknown as RevizComponent },
  { meta: meta_12, Component: Comp_12 as unknown as RevizComponent },
  { meta: meta_13, Component: Comp_13 as unknown as RevizComponent },
  { meta: meta_14, Component: Comp_14 as unknown as RevizComponent },
  { meta: meta_15, Component: Comp_15 as unknown as RevizComponent },
  { meta: meta_16, Component: Comp_16 as unknown as RevizComponent },
  { meta: meta_17, Component: Comp_17 as unknown as RevizComponent },
  { meta: meta_18, Component: Comp_18 as unknown as RevizComponent },
  { meta: meta_19, Component: Comp_19 as unknown as RevizComponent },
  { meta: meta_20, Component: Comp_20 as unknown as RevizComponent },
  { meta: meta_21, Component: Comp_21 as unknown as RevizComponent },
  { meta: meta_22, Component: Comp_22 as unknown as RevizComponent },
  { meta: meta_23, Component: Comp_23 as unknown as RevizComponent },
  { meta: meta_24, Component: Comp_24 as unknown as RevizComponent },
  { meta: meta_25, Component: Comp_25 as unknown as RevizComponent },
  { meta: meta_26, Component: Comp_26 as unknown as RevizComponent },
  { meta: meta_27, Component: Comp_27 as unknown as RevizComponent },
  { meta: meta_28, Component: Comp_28 as unknown as RevizComponent },
  { meta: meta_29, Component: Comp_29 as unknown as RevizComponent },
  { meta: meta_30, Component: Comp_30 as unknown as RevizComponent },
  { meta: meta_31, Component: Comp_31 as unknown as RevizComponent },
  { meta: meta_32, Component: Comp_32 as unknown as RevizComponent },
  { meta: meta_33, Component: Comp_33 as unknown as RevizComponent },
  { meta: meta_34, Component: Comp_34 as unknown as RevizComponent },
  { meta: meta_35, Component: Comp_35 as unknown as RevizComponent },
  { meta: meta_36, Component: Comp_36 as unknown as RevizComponent },
  { meta: meta_37, Component: Comp_37 as unknown as RevizComponent },
  { meta: meta_38, Component: Comp_38 as unknown as RevizComponent },
  { meta: meta_39, Component: Comp_39 as unknown as RevizComponent },
  { meta: meta_40, Component: Comp_40 as unknown as RevizComponent },
  { meta: meta_41, Component: Comp_41 as unknown as RevizComponent },
  { meta: meta_42, Component: Comp_42 as unknown as RevizComponent },
  { meta: meta_43, Component: Comp_43 as unknown as RevizComponent },
  { meta: meta_44, Component: Comp_44 as unknown as RevizComponent },
  { meta: meta_45, Component: Comp_45 as unknown as RevizComponent },
  { meta: meta_46, Component: Comp_46 as unknown as RevizComponent },
  { meta: meta_47, Component: Comp_47 as unknown as RevizComponent },
  { meta: meta_48, Component: Comp_48 as unknown as RevizComponent },
  { meta: meta_49, Component: Comp_49 as unknown as RevizComponent },
  { meta: meta_50, Component: Comp_50 as unknown as RevizComponent },
  { meta: meta_51, Component: Comp_51 as unknown as RevizComponent },
  { meta: meta_52, Component: Comp_52 as unknown as RevizComponent },
  { meta: meta_53, Component: Comp_53 as unknown as RevizComponent },
  { meta: meta_54, Component: Comp_54 as unknown as RevizComponent },
  { meta: meta_55, Component: Comp_55 as unknown as RevizComponent },
  { meta: meta_56, Component: Comp_56 as unknown as RevizComponent },
  { meta: meta_57, Component: Comp_57 as unknown as RevizComponent },
  { meta: meta_58, Component: Comp_58 as unknown as RevizComponent },
  { meta: meta_59, Component: Comp_59 as unknown as RevizComponent },
  { meta: meta_60, Component: Comp_60 as unknown as RevizComponent },
  { meta: meta_61, Component: Comp_61 as unknown as RevizComponent },
  { meta: meta_62, Component: Comp_62 as unknown as RevizComponent },
  { meta: meta_63, Component: Comp_63 as unknown as RevizComponent },
  { meta: meta_64, Component: Comp_64 as unknown as RevizComponent },
  { meta: meta_65, Component: Comp_65 as unknown as RevizComponent },
  { meta: meta_66, Component: Comp_66 as unknown as RevizComponent },
  { meta: meta_67, Component: Comp_67 as unknown as RevizComponent },
  { meta: meta_68, Component: Comp_68 as unknown as RevizComponent },
  { meta: meta_69, Component: Comp_69 as unknown as RevizComponent },
  { meta: meta_70, Component: Comp_70 as unknown as RevizComponent },
  { meta: meta_71, Component: Comp_71 as unknown as RevizComponent },
  { meta: meta_72, Component: Comp_72 as unknown as RevizComponent },
  { meta: meta_73, Component: Comp_73 as unknown as RevizComponent },
  { meta: meta_74, Component: Comp_74 as unknown as RevizComponent },
  { meta: meta_75, Component: Comp_75 as unknown as RevizComponent },
  { meta: meta_76, Component: Comp_76 as unknown as RevizComponent },
  { meta: meta_77, Component: Comp_77 as unknown as RevizComponent },
  { meta: meta_78, Component: Comp_78 as unknown as RevizComponent },
  { meta: meta_79, Component: Comp_79 as unknown as RevizComponent },
  { meta: meta_80, Component: Comp_80 as unknown as RevizComponent },
  { meta: meta_81, Component: Comp_81 as unknown as RevizComponent },
  { meta: meta_82, Component: Comp_82 as unknown as RevizComponent },
  { meta: meta_83, Component: Comp_83 as unknown as RevizComponent },
  { meta: meta_84, Component: Comp_84 as unknown as RevizComponent },
  { meta: meta_85, Component: Comp_85 as unknown as RevizComponent },
  { meta: meta_86, Component: Comp_86 as unknown as RevizComponent },
  { meta: meta_87, Component: Comp_87 as unknown as RevizComponent },
  { meta: meta_88, Component: Comp_88 as unknown as RevizComponent },
  { meta: meta_89, Component: Comp_89 as unknown as RevizComponent },
  { meta: meta_90, Component: Comp_90 as unknown as RevizComponent },
  { meta: meta_91, Component: Comp_91 as unknown as RevizComponent },
  { meta: meta_92, Component: Comp_92 as unknown as RevizComponent },
  { meta: meta_93, Component: Comp_93 as unknown as RevizComponent },
  { meta: meta_94, Component: Comp_94 as unknown as RevizComponent },
  { meta: meta_95, Component: Comp_95 as unknown as RevizComponent },
  { meta: meta_96, Component: Comp_96 as unknown as RevizComponent },
  { meta: meta_97, Component: Comp_97 as unknown as RevizComponent },
  { meta: meta_98, Component: Comp_98 as unknown as RevizComponent },
  { meta: meta_99, Component: Comp_99 as unknown as RevizComponent },
  { meta: meta_100, Component: Comp_100 as unknown as RevizComponent },
  { meta: meta_101, Component: Comp_101 as unknown as RevizComponent },
  { meta: meta_102, Component: Comp_102 as unknown as RevizComponent },
  { meta: meta_103, Component: Comp_103 as unknown as RevizComponent },
  { meta: meta_104, Component: Comp_104 as unknown as RevizComponent },
  { meta: meta_105, Component: Comp_105 as unknown as RevizComponent },
  { meta: meta_106, Component: Comp_106 as unknown as RevizComponent },
  { meta: meta_107, Component: Comp_107 as unknown as RevizComponent },
  { meta: meta_108, Component: Comp_108 as unknown as RevizComponent },
  { meta: meta_109, Component: Comp_109 as unknown as RevizComponent },
  { meta: meta_110, Component: Comp_110 as unknown as RevizComponent },
  { meta: meta_111, Component: Comp_111 as unknown as RevizComponent },
  { meta: meta_112, Component: Comp_112 as unknown as RevizComponent },
  { meta: meta_113, Component: Comp_113 as unknown as RevizComponent },
  { meta: meta_114, Component: Comp_114 as unknown as RevizComponent },
  { meta: meta_115, Component: Comp_115 as unknown as RevizComponent },
  { meta: meta_116, Component: Comp_116 as unknown as RevizComponent },
  { meta: meta_117, Component: Comp_117 as unknown as RevizComponent },
  { meta: meta_118, Component: Comp_118 as unknown as RevizComponent },
];
