// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `yarn gen:registry` to regenerate.
/* eslint-disable */
import type { RegistryEntry, RevizComponent } from "./types";

import { meta as meta_0, default as Comp_0 } from "./components/charts/AreaChart";
import { meta as meta_1, default as Comp_1 } from "./components/charts/BarChart";
import { meta as meta_2, default as Comp_2 } from "./components/charts/DonutChart";
import { meta as meta_3, default as Comp_3 } from "./components/charts/GroupedBarChart";
import { meta as meta_4, default as Comp_4 } from "./components/charts/Histogram";
import { meta as meta_5, default as Comp_5 } from "./components/charts/LineChart";
import { meta as meta_6, default as Comp_6 } from "./components/charts/ScatterPlot";
import { meta as meta_7, default as Comp_7 } from "./components/data-display/CalendarHeatmap";
import { meta as meta_8, default as Comp_8 } from "./components/data-display/DataTable";
import { meta as meta_9, default as Comp_9 } from "./components/data-display/ProgressRing";
import { meta as meta_10, default as Comp_10 } from "./components/data-display/StatCard";
import { meta as meta_11, default as Comp_11 } from "./components/diagrams/ArchitectureDiagram";
import { meta as meta_12, default as Comp_12 } from "./components/diagrams/ComparisonDiagram";
import { meta as meta_13, default as Comp_13 } from "./components/diagrams/FlowDiagram";
import { meta as meta_14, default as Comp_14 } from "./components/diagrams/IsometricStack";
import { meta as meta_15, default as Comp_15 } from "./components/diagrams/NumberedSteps";
import { meta as meta_16, default as Comp_16 } from "./components/diagrams/RadialConcept";
import { meta as meta_17, default as Comp_17 } from "./components/interpretability/AnnotatedTranscript";
import { meta as meta_18, default as Comp_18 } from "./components/interpretability/AttentionMatrix";
import { meta as meta_19, default as Comp_19 } from "./components/interpretability/EmbeddingProjector";
import { meta as meta_20, default as Comp_20 } from "./components/interpretability/NLAAutoencoder";
import { meta as meta_21, default as Comp_21 } from "./components/interpretability/TokenProbabilities";
import { meta as meta_22, default as Comp_22 } from "./components/layout-annotation/AnnotationCallout";
import { meta as meta_23, default as Comp_23 } from "./components/layout-annotation/ColorScaleLegend";
import { meta as meta_24, default as Comp_24 } from "./components/layout-annotation/TabGroup";
import { meta as meta_25, default as Comp_25 } from "./components/math/DistributionPDF";
import { meta as meta_26, default as Comp_26 } from "./components/math/EquationBlock";
import { meta as meta_27, default as Comp_27 } from "./components/math/FunctionPlot";
import { meta as meta_28, default as Comp_28 } from "./components/math/MatrixDisplay";
import { meta as meta_29, default as Comp_29 } from "./components/ml-eval/BenchmarkBars";
import { meta as meta_30, default as Comp_30 } from "./components/ml-eval/LatencyPercentiles";
import { meta as meta_31, default as Comp_31 } from "./components/ml-eval/Leaderboard";
import { meta as meta_32, default as Comp_32 } from "./components/ml-eval/LogScaleBars";
import { meta as meta_33, default as Comp_33 } from "./components/ml-eval/MetricScorecard";
import { meta as meta_34, default as Comp_34 } from "./components/ml-eval/ScalingLaw";
import { meta as meta_35, default as Comp_35 } from "./components/ml-eval/TrainingCurve";
import { meta as meta_36, default as Comp_36 } from "./components/robotics-media/CompareSlider";
import { meta as meta_37, default as Comp_37 } from "./components/robotics-media/FrameStrip";
import { meta as meta_38, default as Comp_38 } from "./components/robotics-media/SyntheticDataTimeline";
import { meta as meta_39, default as Comp_39 } from "./components/robotics-media/TabbedCompare";
import { meta as meta_40, default as Comp_40 } from "./components/statistical/BoxPlot";
import { meta as meta_41, default as Comp_41 } from "./components/statistical/CalibrationPlot";
import { meta as meta_42, default as Comp_42 } from "./components/statistical/ConfidenceBand";
import { meta as meta_43, default as Comp_43 } from "./components/statistical/ConfusionMatrix";
import { meta as meta_44, default as Comp_44 } from "./components/statistical/ROCCurve";
import { meta as meta_45, default as Comp_45 } from "./components/text-narrative/HighlightText";
import { meta as meta_46, default as Comp_46 } from "./components/text-narrative/KeyInsight";
import { meta as meta_47, default as Comp_47 } from "./components/text-narrative/PullQuote";
import { meta as meta_48, default as Comp_48 } from "./components/trees-graphs/DecisionTree";
import { meta as meta_49, default as Comp_49 } from "./components/trees-graphs/ForceGraph";
import { meta as meta_50, default as Comp_50 } from "./components/trees-graphs/SankeyDiagram";
import { meta as meta_51, default as Comp_51 } from "./components/trees-graphs/SearchTree";
import { meta as meta_52, default as Comp_52 } from "./components/trees-graphs/Treemap";

export const REGISTRY: RegistryEntry[] = [
  { meta: meta_0, Component: Comp_0 as unknown as RevizComponent },
  { meta: meta_1, Component: Comp_1 as unknown as RevizComponent },
  { meta: meta_2, Component: Comp_2 as unknown as RevizComponent },
  { meta: meta_3, Component: Comp_3 as unknown as RevizComponent },
  { meta: meta_4, Component: Comp_4 as unknown as RevizComponent },
  { meta: meta_5, Component: Comp_5 as unknown as RevizComponent },
  { meta: meta_6, Component: Comp_6 as unknown as RevizComponent },
  { meta: meta_7, Component: Comp_7 as unknown as RevizComponent },
  { meta: meta_8, Component: Comp_8 as unknown as RevizComponent },
  { meta: meta_9, Component: Comp_9 as unknown as RevizComponent },
  { meta: meta_10, Component: Comp_10 as unknown as RevizComponent },
  { meta: meta_11, Component: Comp_11 as unknown as RevizComponent },
  { meta: meta_12, Component: Comp_12 as unknown as RevizComponent },
  { meta: meta_13, Component: Comp_13 as unknown as RevizComponent },
  { meta: meta_14, Component: Comp_14 as unknown as RevizComponent },
  { meta: meta_15, Component: Comp_15 as unknown as RevizComponent },
  { meta: meta_16, Component: Comp_16 as unknown as RevizComponent },
  { meta: meta_17, Component: Comp_17 as unknown as RevizComponent },
  { meta: meta_18, Component: Comp_18 as unknown as RevizComponent },
  { meta: meta_19, Component: Comp_19 as unknown as RevizComponent },
  { meta: meta_20, Component: Comp_20 as unknown as RevizComponent },
  { meta: meta_21, Component: Comp_21 as unknown as RevizComponent },
  { meta: meta_22, Component: Comp_22 as unknown as RevizComponent },
  { meta: meta_23, Component: Comp_23 as unknown as RevizComponent },
  { meta: meta_24, Component: Comp_24 as unknown as RevizComponent },
  { meta: meta_25, Component: Comp_25 as unknown as RevizComponent },
  { meta: meta_26, Component: Comp_26 as unknown as RevizComponent },
  { meta: meta_27, Component: Comp_27 as unknown as RevizComponent },
  { meta: meta_28, Component: Comp_28 as unknown as RevizComponent },
  { meta: meta_29, Component: Comp_29 as unknown as RevizComponent },
  { meta: meta_30, Component: Comp_30 as unknown as RevizComponent },
  { meta: meta_31, Component: Comp_31 as unknown as RevizComponent },
  { meta: meta_32, Component: Comp_32 as unknown as RevizComponent },
  { meta: meta_33, Component: Comp_33 as unknown as RevizComponent },
  { meta: meta_34, Component: Comp_34 as unknown as RevizComponent },
  { meta: meta_35, Component: Comp_35 as unknown as RevizComponent },
  { meta: meta_36, Component: Comp_36 as unknown as RevizComponent },
  { meta: meta_37, Component: Comp_37 as unknown as RevizComponent },
  { meta: meta_38, Component: Comp_38 as unknown as RevizComponent },
  { meta: meta_39, Component: Comp_39 as unknown as RevizComponent },
  { meta: meta_40, Component: Comp_40 as unknown as RevizComponent },
  { meta: meta_41, Component: Comp_41 as unknown as RevizComponent },
  { meta: meta_42, Component: Comp_42 as unknown as RevizComponent },
  { meta: meta_43, Component: Comp_43 as unknown as RevizComponent },
  { meta: meta_44, Component: Comp_44 as unknown as RevizComponent },
  { meta: meta_45, Component: Comp_45 as unknown as RevizComponent },
  { meta: meta_46, Component: Comp_46 as unknown as RevizComponent },
  { meta: meta_47, Component: Comp_47 as unknown as RevizComponent },
  { meta: meta_48, Component: Comp_48 as unknown as RevizComponent },
  { meta: meta_49, Component: Comp_49 as unknown as RevizComponent },
  { meta: meta_50, Component: Comp_50 as unknown as RevizComponent },
  { meta: meta_51, Component: Comp_51 as unknown as RevizComponent },
  { meta: meta_52, Component: Comp_52 as unknown as RevizComponent },
];
